### ISSUE TITLE
Mbusd as TCP client and TCP master at the same time

### ISSUE THREAD

**Issue by kinkazu** [3cky/mbusd#51] opened 2019-05-26 18:20 UTC
Hi. I have Modbus TCP slave which accept only one master and I would like to connect more to it. I believe it wouldn’t be that difficult for you gentleman to add extra function to mbusd to sort out this issue.
This might be useful to more people than me and could extend your great application by extra function?
Maybe you have any other ideas?
Big mbusd fan.
Kind regards

**Comment by 3cky** [comment] 2019-05-27 08:21
Duplicate of #48

**Comment by 3cky** [comment] 2019-05-27 08:23
Please follow the discussion in #48

**Closed by 3cky** 2019-05-27 08:23 UTC
